kind: Deployment
apiVersion: apps/v1
metadata:
  name: curvefs-csi-controller
  namespace: curvefs
spec:
  selector:
    matchLabels:
      app: curvefs-csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: curvefs-csi-controller
    spec:
      serviceAccount: curvefs-csi-service-account
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.6.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --provisioner=csi.curvefs.com
            - --csi-address=$(ADDRESS)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi-controller.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          # limits:
          #   cpu: 500m
          #   memory: 512Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: curvefs-driver
          # Different back-end curve cluster using different image
          # for v2.4.0-beta2:  curvecsi/curvefscsi:v1.0.1
          # for v2.5.0-beta:  curvecsi/curvefscsi:v1.0.2
          image: curvecsi/curvefscsi:2.6.0-hotfix-b93e91e
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(NODE_NAME)
            - --alsologtostderr
            - --v=5
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CSI_ENDPOINT
              value: unix:///csi/csi-controller.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "rm -rf /csi/csi-controller.sock"
                ]
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /curvefs/client/logs
              mountPropagation: Bidirectional
              name: logs-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.curvefs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: mountpoint-dir
        - hostPath:
            path: /data/vmtsdb/csilogs
            type: DirectoryOrCreate
          name: logs-dir

