apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-curvefs-pvc
  namespace: curvefs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
  storageClassName: curvefs-sc
